#!/bin/bash 

DB_USER='root'
DB_PASS='12345'
DB='test'

echo 'logging into db test as root'
#mysql -u "$DB_USER" --password="$DB_PASS" --database="$DB"

function _debug()
{
    [ "$DEBUG" -eq 1 ] && $@
}

function _stop()
{
    exit 0
}

while [ "true" ]; do 
mysql -u "$DB_USER" --password="$DB_PASS" --database="$DB" -e "INSERT INTO "taxi" ("time") VALUES ('6');"
sleep $((RANDOM%20+5))
done